
language: php
dist: trusty
sudo: false

matrix:
  include:
    - php: 7.2
      env: FRAMEWORK_VERSION=laravel/framework:5.8.*

before_install:
  - printf "\n" | w

install:
  - composer require "${FRAMEWORK_VERSION}" --no-update -n
  - travis_retry composer install --no-suggest --prefer-dist -n -o

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/php-coveralls -v